DROP TABLE public.log_tb;

CREATE TABLE public.log_tb
(
    log_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date timestamp ,
    log_ip character varying(255) COLLATE pg_catalog."default",
    log_request character varying(255) COLLATE pg_catalog."default",
    log_status integer,
    log_useragent character varying(255) COLLATE pg_catalog."default"
)